### PR TITLE
Fix html being injected into all responses

### PR DESCRIPTION
**Pull request by krve**
This caused API calls to have the html returned after the json. Example:

1. I make an ajax request to `/api/user`
2. It returns the user, directly followed by the html for the user-selector.

image

This should fix the issue by checking if the request expects json.

### CODE REVIEW

**Comment by krve** [comment]
There should probably also be some way to specify routes that should have the html injected. Like if you have a route that returns string, etc.

**Comment by krve** [comment]
I've changed the way it works to now use a simple partial  and I've also updated the readme to reflect the changes.

@mrterryh could you have a look and see if anything stands out?

**Comment by mrterryh** [comment]
I've just made a couple of small changes (mainly formatting). I'll review and merge this over the weekend, thanks for your help @krve! Really pleased with this :)

**Comment by krve** [comment]
No problem :smile:

**Pull request merged**
